### ISSUE TITLE
Pre Footer: Map did not display the correct location

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/JJKings#15]
![image](https://cloud.githubusercontent.com/assets/12888048/16724273/8468dcd2-4784-11e6-843e-743d07d9499d.png)

**Comment by devinci** [comment]
Fixed. Displays dynamic location

**Comment by romatitan** [comment]
![image](https://cloud.githubusercontent.com/assets/12888048/17244244/7b76dcae-55b3-11e6-8a4a-db118f9da26b.png)
![image](https://cloud.githubusercontent.com/assets/12888048/17244249/7dcf2c7c-55b3-11e6-8589-b6a9aa171999.png)

**Comment by devinci** [comment]
Due to the inherit inaccuracy of geocoding addresses via the API, to maintain accurate results, the actual physical address needs to be set via the Map Location tab in the homepage settings section. 

![image](https://cloud.githubusercontent.com/assets/7167770/17580415/c286dfd2-5f9e-11e6-8203-5f4ea9cde984.png)

Please be aware that the infobubble will still display the address listed under business details on homepage and these should be adjusted to match the location specified in the map section.

- via Jonathan
